[package]
name = "jonect_android_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
audiopus = "0.3.0-rc.0"
jni = "0.19.0"
ndk-sys = "0.2.2"
libc = "0.2.112"

[lib]
crate-type = ["cdylib"]
